abstract: TWMOE Chinese Phrase Dictionary interface.
author: Kang-min Liu, C<< <gugod at gugod.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WWW-Dict-TWMOE-Phrase
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Field: 0
  Encode: 0
  HTML::TableExtract: 0
  HTML::TagParser: 0
  WWW::Mechanize: 0
version: 0.03
